--INSERT ingredients (separated by category)
START TRANSACTION;
--Veggies
INSERT INTO ingredient(name, category) VALUES ('Artichoke', 'Vegetable');
INSERT INTO ingredient(name, category) VALUES ('Avocado', 'Vegetable');
INSERT INTO ingredient(name, category) VALUES ('Beans', 'Vegetable');
INSERT INTO ingredient(name, category) VALUES ('Beets', 'Vegetable');
INSERT INTO ingredient(name, category) VALUES ('Broccoli', 'Vegetable');
INSERT INTO ingredient(name, category) VALUES ('Cabbage', 'Vegetable');
INSERT INTO ingredient(name, category) VALUES ('Carrot', 'Vegetable');
INSERT INTO ingredient(name, category) VALUES ('Cauliflower', 'Vegetable');
INSERT INTO ingredient(name, category) VALUES ('Celery', 'Vegetable');
INSERT INTO ingredient(name, category) VALUES ('Collard Greens', 'Vegetable');
INSERT INTO ingredient(name, category) VALUES ('Corn', 'Vegetable');
INSERT INTO ingredient(name, category) VALUES ('Cucumber', 'Vegetable');
INSERT INTO ingredient(name, category) VALUES ('Eggplant', 'Vegetable');
INSERT INTO ingredient(name, category) VALUES ('Garlic', 'Vegetable');
INSERT INTO ingredient(name, category) VALUES ('Green Beans', 'Vegetable');
INSERT INTO ingredient(name, category) VALUES ('Green Onions', 'Vegetable');
INSERT INTO ingredient(name, category) VALUES ('Green Pepper', 'Vegetable');
INSERT INTO ingredient(name, category) VALUES ('Kale', 'Vegetable');
INSERT INTO ingredient(name, category) VALUES ('Lettuce', 'Vegetable');
INSERT INTO ingredient(name, category) VALUES ('Mushrooms', 'Vegetable');
INSERT INTO ingredient(name, category) VALUES ('Olives', 'Vegetable');
INSERT INTO ingredient(name, category) VALUES ('Onion', 'Vegetable');
INSERT INTO ingredient(name, category) VALUES ('Peas', 'Vegetable');
INSERT INTO ingredient(name, category) VALUES ('Potato', 'Vegetable');
INSERT INTO ingredient(name, category) VALUES ('Pumpkin', 'Vegetable');
INSERT INTO ingredient(name, category) VALUES ('Radish', 'Vegetable');
INSERT INTO ingredient(name, category) VALUES ('Red Pepper', 'Vegetable');
INSERT INTO ingredient(name, category) VALUES ('Shallots', 'Vegetable');
INSERT INTO ingredient(name, category) VALUES ('Spinach', 'Vegetable');
INSERT INTO ingredient(name, category) VALUES ('Squash', 'Vegetable');
INSERT INTO ingredient(name, category) VALUES ('Tomato', 'Vegetable');
INSERT INTO ingredient(name, category) VALUES ('Yam', 'Vegetable');
INSERT INTO ingredient(name, category) VALUES ('Zucchini', 'Vegetable');

--fruits
INSERT INTO ingredient(name, category) VALUES ('Apple', 'Fruit');
INSERT INTO ingredient(name, category) VALUES ('Apricot', 'Fruit');
INSERT INTO ingredient(name, category) VALUES ('Banana', 'Fruit');
INSERT INTO ingredient(name, category) VALUES ('Blackberry', 'Fruit');
INSERT INTO ingredient(name, category) VALUES ('Blueberry', 'Fruit');
INSERT INTO ingredient(name, category) VALUES ('Coconut', 'Fruit');
INSERT INTO ingredient(name, category) VALUES ('Cranberry', 'Fruit');
INSERT INTO ingredient(name, category) VALUES ('Grapefruit', 'Fruit');
INSERT INTO ingredient(name, category) VALUES ('Grapes', 'Fruit');
INSERT INTO ingredient(name, category) VALUES ('Lemon', 'Fruit');
INSERT INTO ingredient(name, category) VALUES ('Lime', 'Fruit');
INSERT INTO ingredient(name, category) VALUES ('Mango', 'Fruit');
INSERT INTO ingredient(name, category) VALUES ('Orange', 'Fruit');
INSERT INTO ingredient(name, category) VALUES ('Peach', 'Fruit');
INSERT INTO ingredient(name, category) VALUES ('Pear', 'Fruit');
INSERT INTO ingredient(name, category) VALUES ('Pineapple', 'Fruit');
INSERT INTO ingredient(name, category) VALUES ('Plum', 'Fruit');
INSERT INTO ingredient(name, category) VALUES ('Pomegranate', 'Fruit');
INSERT INTO ingredient(name, category) VALUES ('Raspberry', 'Fruit');
INSERT INTO ingredient(name, category) VALUES ('Strawberry', 'Fruit');
INSERT INTO ingredient(name, category) VALUES ('Watermelon', 'Fruit');

--dairy/animal products
INSERT INTO ingredient(name, category) VALUES ('American Cheese', 'Dairy/Animal Products');
INSERT INTO ingredient(name, category) VALUES ('Blue Cheese', 'Dairy/Animal Products');
INSERT INTO ingredient(name, category) VALUES ('Butter', 'Dairy/Animal Products');
INSERT INTO ingredient(name, category) VALUES ('Cheddar Cheese', 'Dairy/Animal Products');
INSERT INTO ingredient(name, category) VALUES ('Coconut Milk', 'Dairy/Animal Products');
INSERT INTO ingredient(name, category) VALUES ('Cottage Cheese', 'Dairy/Animal Products');
INSERT INTO ingredient(name, category) VALUES ('Cream', 'Dairy/Animal Products');
INSERT INTO ingredient(name, category) VALUES ('Cream Cheese', 'Dairy/Animal Products');
INSERT INTO ingredient(name, category) VALUES ('Eggs', 'Dairy/Animal Products');
INSERT INTO ingredient(name, category) VALUES ('Feta Cheese', 'Dairy/Animal Products');
INSERT INTO ingredient(name, category) VALUES ('Goat Cheese', 'Dairy/Animal Products');
INSERT INTO ingredient(name, category) VALUES ('Half and Half', 'Dairy/Animal Products');
INSERT INTO ingredient(name, category) VALUES ('Heavy Cream', 'Dairy/Animal Products');
INSERT INTO ingredient(name, category) VALUES ('Ice Cream', 'Dairy/Animal Products');
INSERT INTO ingredient(name, category) VALUES ('Mayonaise', 'Dairy/Animal Products');
INSERT INTO ingredient(name, category) VALUES ('Milk', 'Dairy/Animal Products');
INSERT INTO ingredient(name, category) VALUES ('Monterey Jack Cheese', 'Dairy/Animal Products');
INSERT INTO ingredient(name, category) VALUES ('Mozzarella Cheese', 'Dairy/Animal Products');
INSERT INTO ingredient(name, category) VALUES ('Parmesan Cheese', 'Dairy/Animal Products');
INSERT INTO ingredient(name, category) VALUES ('Pepper Jack Cheese', 'Dairy/Animal Products');
INSERT INTO ingredient(name, category) VALUES ('Provolone Cheese', 'Dairy/Animal Products');
INSERT INTO ingredient(name, category) VALUES ('Ricotta Cheese', 'Dairy/Animal Products');
INSERT INTO ingredient(name, category) VALUES ('Sour Cream', 'Dairy/Animal Products');
INSERT INTO ingredient(name, category) VALUES ('Swiss Cheese', 'Dairy/Animal Products');
INSERT INTO ingredient(name, category) VALUES ('Velveeta Cheese', 'Dairy/Animal Products');
INSERT INTO ingredient(name, category) VALUES ('Yogurt', 'Dairy/Animal Products');

--meat
INSERT INTO ingredient(name, category) VALUES ('Bacon', 'Meat');
INSERT INTO ingredient(name, category) VALUES ('Beef', 'Meat');
INSERT INTO ingredient(name, category) VALUES ('Bologna', 'Meat');
INSERT INTO ingredient(name, category) VALUES ('Chicken', 'Meat');
INSERT INTO ingredient(name, category) VALUES ('Ham', 'Meat');
INSERT INTO ingredient(name, category) VALUES ('Hot Dog', 'Meat');
INSERT INTO ingredient(name, category) VALUES ('Lamb', 'Meat');
INSERT INTO ingredient(name, category) VALUES ('Meatballs', 'Meat');
INSERT INTO ingredient(name, category) VALUES ('Pepperoni', 'Meat');
INSERT INTO ingredient(name, category) VALUES ('Pork', 'Meat');
INSERT INTO ingredient(name, category) VALUES ('Pork Chops', 'Meat');
INSERT INTO ingredient(name, category) VALUES ('Pork Roast', 'Meat');
INSERT INTO ingredient(name, category) VALUES ('Prosciutto', 'Meat');
INSERT INTO ingredient(name, category) VALUES ('Roast Beef', 'Meat');
INSERT INTO ingredient(name, category) VALUES ('Salami', 'Meat');
INSERT INTO ingredient(name, category) VALUES ('Sausage', 'Meat');
INSERT INTO ingredient(name, category) VALUES ('Steak', 'Meat');
INSERT INTO ingredient(name, category) VALUES ('Turkey', 'Meat');

--fish/seafood
INSERT INTO ingredient(name, category) VALUES ('Bass', 'Fish/Seafood');
INSERT INTO ingredient(name, category) VALUES ('Catfish', 'Fish/Seafood');
INSERT INTO ingredient(name, category) VALUES ('Clam', 'Fish/Seafood');
INSERT INTO ingredient(name, category) VALUES ('Crab', 'Fish/Seafood');
INSERT INTO ingredient(name, category) VALUES ('Flounder', 'Fish/Seafood');
INSERT INTO ingredient(name, category) VALUES ('Lobster', 'Fish/Seafood');
INSERT INTO ingredient(name, category) VALUES ('Mussel', 'Fish/Seafood');
INSERT INTO ingredient(name, category) VALUES ('Oyster', 'Fish/Seafood');
INSERT INTO ingredient(name, category) VALUES ('Salmon', 'Fish/Seafood');
INSERT INTO ingredient(name, category) VALUES ('Shrimp', 'Fish/Seafood');
INSERT INTO ingredient(name, category) VALUES ('Tilapia', 'Fish/Seafood');
INSERT INTO ingredient(name, category) VALUES ('Trout', 'Fish/Seafood');
INSERT INTO ingredient(name, category) VALUES ('Tuna', 'Fish/Seafood');

--nuts
INSERT INTO ingredient(name, category) VALUES ('Almond', 'Nuts');
INSERT INTO ingredient(name, category) VALUES ('Cashew', 'Nuts');
INSERT INTO ingredient(name, category) VALUES ('Hazelnut', 'Nuts');
INSERT INTO ingredient(name, category) VALUES ('Peanut', 'Nuts');
INSERT INTO ingredient(name, category) VALUES ('Pecan', 'Nuts');
INSERT INTO ingredient(name, category) VALUES ('Walnut', 'Nuts');

--grains/carbs
INSERT INTO ingredient(name, category) VALUES ('Bread', 'Grains/Carbs');
INSERT INTO ingredient(name, category) VALUES ('Flour', 'Grains/Carbs');
INSERT INTO ingredient(name, category) VALUES ('Pasta', 'Grains/Carbs');
INSERT INTO ingredient(name, category) VALUES ('Quinoa', 'Grains/Carbs');
INSERT INTO ingredient(name, category) VALUES ('Rice', 'Grains/Carbs');

--spices/seasonings
INSERT INTO ingredient(name, category) VALUES ('Allspice', 'Spices/Seasonings');
INSERT INTO ingredient(name, category) VALUES ('Baking Powder', 'Spices/Seasonings');
INSERT INTO ingredient(name, category) VALUES ('Baking Soda', 'Spices/Seasonings');
INSERT INTO ingredient(name, category) VALUES ('Bay Leaves', 'Spices/Seasonings');
INSERT INTO ingredient(name, category) VALUES ('Brown Sugar', 'Spices/Seasonings');
INSERT INTO ingredient(name, category) VALUES ('Canola Oil', 'Spices/Seasonings');
INSERT INTO ingredient(name, category) VALUES ('Cayenne Pepper', 'Spices/Seasonings');
INSERT INTO ingredient(name, category) VALUES ('Chili Seasoning', 'Spices/Seasonings');
INSERT INTO ingredient(name, category) VALUES ('Chocolate', 'Spices/Seasonings');
INSERT INTO ingredient(name, category) VALUES ('Cilantro', 'Spices/Seasonings');
INSERT INTO ingredient(name, category) VALUES ('Cloves', 'Spices/Seasonings');
INSERT INTO ingredient(name, category) VALUES ('Coconut Oil', 'Spices/Seasonings');
INSERT INTO ingredient(name, category) VALUES ('Corn Oil', 'Spices/Seasonings');
INSERT INTO ingredient(name, category) VALUES ('Corn Starch', 'Spices/Seasonings');
INSERT INTO ingredient(name, category) VALUES ('Cumin', 'Spices/Seasonings');
INSERT INTO ingredient(name, category) VALUES ('Curry Powder', 'Spices/Seasonings');
INSERT INTO ingredient(name, category) VALUES ('Dry Mustard', 'Spices/Seasonings');
INSERT INTO ingredient(name, category) VALUES ('Garlic Powder', 'Spices/Seasonings');
INSERT INTO ingredient(name, category) VALUES ('Ginger', 'Spices/Seasonings');
INSERT INTO ingredient(name, category) VALUES ('Honey', 'Spices/Seasonings');
INSERT INTO ingredient(name, category) VALUES ('Lemon Extract', 'Spices/Seasonings');
INSERT INTO ingredient(name, category) VALUES ('Mint', 'Spices/Seasonings');
INSERT INTO ingredient(name, category) VALUES ('Nutmeg', 'Spices/Seasonings');
INSERT INTO ingredient(name, category) VALUES ('Olive Oil', 'Spices/Seasonings');
INSERT INTO ingredient(name, category) VALUES ('Onion Powder', 'Spices/Seasonings');
INSERT INTO ingredient(name, category) VALUES ('Oregano', 'Spices/Seasonings');
INSERT INTO ingredient(name, category) VALUES ('Paprika', 'Spices/Seasonings');
INSERT INTO ingredient(name, category) VALUES ('Parsley', 'Spices/Seasonings');
INSERT INTO ingredient(name, category) VALUES ('Pepper', 'Spices/Seasonings');
INSERT INTO ingredient(name, category) VALUES ('Ranch Mix', 'Spices/Seasonings');
INSERT INTO ingredient(name, category) VALUES ('Rosemary', 'Spices/Seasonings');
INSERT INTO ingredient(name, category) VALUES ('Salt', 'Spices/Seasonings');
INSERT INTO ingredient(name, category) VALUES ('Sazon', 'Spices/Seasonings');
INSERT INTO ingredient(name, category) VALUES ('Sesame Oil', 'Spices/Seasonings');
INSERT INTO ingredient(name, category) VALUES ('Sugar', 'Spices/Seasonings');
INSERT INTO ingredient(name, category) VALUES ('Taco Seasoning', 'Spices/Seasonings');
INSERT INTO ingredient(name, category) VALUES ('Thyme', 'Spices/Seasonings');
INSERT INTO ingredient(name, category) VALUES ('Tumeric', 'Spices/Seasonings');
INSERT INTO ingredient(name, category) VALUES ('Vanilla Extract', 'Spices/Seasonings');
INSERT INTO ingredient(name, category) VALUES ('White Pepper', 'Spices/Seasonings');

--condiments
INSERT INTO ingredient(name, category) VALUES ('Apple Cider Vinegar', 'Condiments');
INSERT INTO ingredient(name, category) VALUES ('Balsamic Vinegar', 'Condiments');
INSERT INTO ingredient(name, category) VALUES ('Barbecue Sauce', 'Condiments');
INSERT INTO ingredient(name, category) VALUES ('Brown Mustard', 'Condiments');
INSERT INTO ingredient(name, category) VALUES ('Buffalo Sauce', 'Condiments');
INSERT INTO ingredient(name, category) VALUES ('Burgandy Wine', 'Condiments');
INSERT INTO ingredient(name, category) VALUES ('Caramel', 'Condiments');
INSERT INTO ingredient(name, category) VALUES ('Caesar Dressing', 'Condiments');
INSERT INTO ingredient(name, category) VALUES ('Cheese Whiz', 'Condiments');
INSERT INTO ingredient(name, category) VALUES ('Chili Sauce', 'Condiments');
INSERT INTO ingredient(name, category) VALUES ('Chocolate Syrup', 'Condiments');
INSERT INTO ingredient(name, category) VALUES ('Cocktail Sauce', 'Condiments');
INSERT INTO ingredient(name, category) VALUES ('Corn Syrup', 'Condiments');
INSERT INTO ingredient(name, category) VALUES ('Cranberry Sauce', 'Condiments');
INSERT INTO ingredient(name, category) VALUES ('Curry Sauce', 'Condiments');
INSERT INTO ingredient(name, category) VALUES ('Dijon Mustard', 'Condiments');
INSERT INTO ingredient(name, category) VALUES ('French Dressing', 'Condiments');
INSERT INTO ingredient(name, category) VALUES ('Garlic Sauce', 'Condiments');
INSERT INTO ingredient(name, category) VALUES ('Grape Jelly', 'Condiments');
INSERT INTO ingredient(name, category) VALUES ('Gravy', 'Condiments');
INSERT INTO ingredient(name, category) VALUES ('Guacamole', 'Condiments');
INSERT INTO ingredient(name, category) VALUES ('Honey Mustard', 'Condiments');
INSERT INTO ingredient(name, category) VALUES ('Horseradish', 'Condiments');
INSERT INTO ingredient(name, category) VALUES ('Italian Dressing', 'Condiments');
INSERT INTO ingredient(name, category) VALUES ('Jam', 'Condiments');
INSERT INTO ingredient(name, category) VALUES ('Ketchup', 'Condiments');
INSERT INTO ingredient(name, category) VALUES ('Maple Syrup', 'Condiments');
INSERT INTO ingredient(name, category) VALUES ('Marsala Wine', 'Condiments');
INSERT INTO ingredient(name, category) VALUES ('Marinara', 'Condiments');
INSERT INTO ingredient(name, category) VALUES ('Mayonnaise', 'Condiments');
INSERT INTO ingredient(name, category) VALUES ('Miracle Whip', 'Condiments');
INSERT INTO ingredient(name, category) VALUES ('Molasses', 'Condiments');
INSERT INTO ingredient(name, category) VALUES ('Nutella', 'Condiments');
INSERT INTO ingredient(name, category) VALUES ('Orange Jelly', 'Condiments');
INSERT INTO ingredient(name, category) VALUES ('Oyster Sauce', 'Condiments');
INSERT INTO ingredient(name, category) VALUES ('Peanut Butter', 'Condiments');
INSERT INTO ingredient(name, category) VALUES ('Pesto', 'Condiments');
INSERT INTO ingredient(name, category) VALUES ('Poppy Seed Dressing', 'Condiments');
INSERT INTO ingredient(name, category) VALUES ('Red Vinegar', 'Condiments');
INSERT INTO ingredient(name, category) VALUES ('Red Wine Vinegar', 'Condiments');
INSERT INTO ingredient(name, category) VALUES ('Ranch Dressing', 'Condiments');
INSERT INTO ingredient(name, category) VALUES ('Red Wine', 'Condiments');
INSERT INTO ingredient(name, category) VALUES ('Relish', 'Condiments');
INSERT INTO ingredient(name, category) VALUES ('Salsa', 'Condiments');
INSERT INTO ingredient(name, category) VALUES ('Sherry Wine', 'Condiments');
INSERT INTO ingredient(name, category) VALUES ('Soy Sauce', 'Condiments');
INSERT INTO ingredient(name, category) VALUES ('Steak Sauce', 'Condiments');
INSERT INTO ingredient(name, category) VALUES ('Teriyaki Sauce', 'Condiments');
INSERT INTO ingredient(name, category) VALUES ('Thousand Island Dressing', 'Condiments');
INSERT INTO ingredient(name, category) VALUES ('Tobasco Sauce', 'Condiments');
INSERT INTO ingredient(name, category) VALUES ('Tomato Sauce', 'Condiments');
INSERT INTO ingredient(name, category) VALUES ('Vermouth', 'Condiments');
INSERT INTO ingredient(name, category) VALUES ('White Sauce', 'Condiments');
INSERT INTO ingredient(name, category) VALUES ('White Vinegar', 'Condiments');
INSERT INTO ingredient(name, category) VALUES ('White Wine', 'Condiments');
INSERT INTO ingredient(name, category) VALUES ('Worcestershire', 'Condiments');

--commit changes
COMMIT;